//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace IQLog.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IQLogDataContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IQLogDataContext object using the connection string found in the 'IQLogDataContext' section of the application configuration file.
        /// </summary>
        public IQLogDataContext() : base("name=IQLogDataContext", "IQLogDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IQLogDataContext object.
        /// </summary>
        public IQLogDataContext(string connectionString) : base(connectionString, "IQLogDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IQLogDataContext object.
        /// </summary>
        public IQLogDataContext(EntityConnection connection) : base(connection, "IQLogDataContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<EventType> EventTypeSelectAll()
        {
            return base.ExecuteFunction<EventType>("EventTypeSelectAll");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectResult<ProcessType> ProcessTypeSelectAll()
        {
            return base.ExecuteFunction<ProcessType>("ProcessTypeSelectAll");
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="iD">No Metadata Documentation available.</param>
        /// <param name="name">No Metadata Documentation available.</param>
        public int ProcessTypeSelectNameById(Nullable<global::System.Int16> iD, ObjectParameter name)
        {
            ObjectParameter iDParameter;
            if (iD.HasValue)
            {
                iDParameter = new ObjectParameter("ID", iD);
            }
            else
            {
                iDParameter = new ObjectParameter("ID", typeof(global::System.Int16));
            }
    
            return base.ExecuteFunction("ProcessTypeSelectNameById", iDParameter, name);
        }

        #endregion

    }

    #endregion

    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="IQLog.Model", Name="EventType")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class EventType : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new EventType object.
        /// </summary>
        /// <param name="eventCode">Initial value of the EventCode property.</param>
        /// <param name="logLevel">Initial value of the LogLevel property.</param>
        /// <param name="message">Initial value of the Message property.</param>
        public static EventType CreateEventType(global::System.Int16 eventCode, global::System.Int16 logLevel, global::System.String message)
        {
            EventType eventType = new EventType();
            eventType.EventCode = eventCode;
            eventType.LogLevel = logLevel;
            eventType.Message = message;
            return eventType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 EventCode
        {
            get
            {
                return _EventCode;
            }
            set
            {
                OnEventCodeChanging(value);
                ReportPropertyChanging("EventCode");
                _EventCode = StructuralObject.SetValidValue(value, "EventCode");
                ReportPropertyChanged("EventCode");
                OnEventCodeChanged();
            }
        }
        private global::System.Int16 _EventCode;
        partial void OnEventCodeChanging(global::System.Int16 value);
        partial void OnEventCodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 LogLevel
        {
            get
            {
                return _LogLevel;
            }
            set
            {
                OnLogLevelChanging(value);
                ReportPropertyChanging("LogLevel");
                _LogLevel = StructuralObject.SetValidValue(value, "LogLevel");
                ReportPropertyChanged("LogLevel");
                OnLogLevelChanged();
            }
        }
        private global::System.Int16 _LogLevel;
        partial void OnLogLevelChanging(global::System.Int16 value);
        partial void OnLogLevelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Message
        {
            get
            {
                return _Message;
            }
            set
            {
                OnMessageChanging(value);
                ReportPropertyChanging("Message");
                _Message = StructuralObject.SetValidValue(value, false, "Message");
                ReportPropertyChanged("Message");
                OnMessageChanged();
            }
        }
        private global::System.String _Message;
        partial void OnMessageChanging(global::System.String value);
        partial void OnMessageChanged();

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="IQLog.Model", Name="ProcessType")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ProcessType : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProcessType object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static ProcessType CreateProcessType(global::System.Int16 id, global::System.String name)
        {
            ProcessType processType = new ProcessType();
            processType.ID = id;
            processType.Name = name;
            return processType;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                OnIDChanging(value);
                ReportPropertyChanging("ID");
                _ID = StructuralObject.SetValidValue(value, "ID");
                ReportPropertyChanged("ID");
                OnIDChanged();
            }
        }
        private global::System.Int16 _ID;
        partial void OnIDChanging(global::System.Int16 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false, "Name");
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();

        #endregion

    }

    #endregion

}
